### ISSUE TITLE
Test mode

### ISSUE THREAD

**Issue by qsibmini-khu** [EchoRickZz/Pensieve-Pytorch#2]
Is there a testing mode? 
I would like to evaluate the models with different training times 

Thank you.

**Comment by RuixiaoZhang** [comment]
Hi
Actually, the test of the model has been intergerated in the training process, see https://github.com/EchoRickZz/Pensieve-Pytorch/blob/e9327e119dec8baaf927c54879a6e889c9b45466/multi_pytorch.py#L50 

BEST

**Comment by qsibmini-khu** [comment]
> Hi Actually, the test of the model has been intergerated in the training process, see
> 
> https://github.com/EchoRickZz/Pensieve-Pytorch/blob/e9327e119dec8baaf927c54879a6e889c9b45466/multi_pytorch.py#L50
> 
> BEST

Thank you :)

**Comment by RuixiaoZhang** [comment]
> > Hi Actually, the test of the model has been intergerated in the training process, see
> > https://github.com/EchoRickZz/Pensieve-Pytorch/blob/e9327e119dec8baaf927c54879a6e889c9b45466/multi_pytorch.py#L50
> > 
> > BEST
> 
> Thank you :)

:)
